default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: 412294
  url:


development:
  <<: *default
  database: ecommerce_dbc_development

test:
  <<: *default
  database: ecommerce_dbc_test

production:
  primary: &primary_production
    <<: *default
    database: ecommerce_dbc_production
    username: ecommerce_dbc
    password: <%= ENV["ECOMMERCE_DBC_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: ecommerce_dbc_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: ecommerce_dbc_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: ecommerce_dbc_production_cable
    migrations_paths: db/cable_migrate
